version: "3.8"

services:

  server-db:
    image: mariadb:10.6.4-focal
    command: mysqld --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4 --innodb-flush-log-at-trx-commit=0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dontTellAnyone
      MYSQL_DATABASE: opti
    volumes:
      - ./dockervolumes/mariadb/server-db:/var/lib/mysql
    restart: always
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

