
spring:
  datasource:
    url: "jdbc:mariadb://${MARIADB_HOST:localhost}:${MARIADB_PORT:3306}/opti?createDatabaseIfNotExist=true"
    username: root
    password: dontTellAnyone
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: optimistic.lock.extra.JpaPhysicalNamingStrategy
        implicit-strategy: optimistic.lock.extra.JpaImplicitNamingStrategy
  flyway:
    locations: classpath:db

